# ETL
Дана таблица с кодом товара. Зачада - преобразовать даные так, чтобы разбить информацию на столбцы Код, Бренд, Название товара, Размер, Цвет.

## Export

In [171]:
!wget "https://drive.google.com/uc?id=1gU66IzQxkng32TLllicZa2O0F5KDJtDw" -O input_data.csv

--2026-04-03 09:26:11--  https://drive.google.com/uc?id=1gU66IzQxkng32TLllicZa2O0F5KDJtDw
Resolving drive.google.com (drive.google.com)... 74.125.139.102, 74.125.139.100, 74.125.139.101, ...
Connecting to drive.google.com (drive.google.com)|74.125.139.102|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1gU66IzQxkng32TLllicZa2O0F5KDJtDw [following]
--2026-04-03 09:26:11--  https://drive.usercontent.google.com/download?id=1gU66IzQxkng32TLllicZa2O0F5KDJtDw
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 173.194.217.132, 2607:f8b0:400c:c13::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|173.194.217.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 130700 (128K) [application/octet-stream]
Saving to: ‘input_data.csv’

input_data.csv      100%[===================>] 127.64K  --.-KB/s    in 0.001s

2026-04-03 09:26:12 (136 MB/s) - ‘input_data.csv’ saved [130700/130700]

In [172]:
import pandas as pd
import numpy as np
import re

### Загрузка файла

In [173]:
df = pd.read_csv('input_data.csv', sep =';')
df.shape

(972, 14)

In [174]:
df.head()

,Код,шт в упак,м3 упак,нетто упак,брутто упак,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,"PFAN-1107, Döcke Наличник 89 мм/ 30 мм (Белый)",упак (14 шт),"0,146","21,168","22,548",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"PFAN-1193, Döcke Наличник 89 мм/ 30 мм (Шокола...",упак (14 шт),"0,146","21,168","22,548",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"PFAV-1107, Döcke Внешний угол 75 мм/ 30 мм (Бе...",упак (8 шт),"0,145","15,552","16,788",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"PFAV-1193, Döcke Внешний угол 75 мм/ 30 мм (Шо...",упак (8 шт),"0,145","15,552","16,788",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"PFPF-1039, Döcke Профиль J18 (Карамельный)",упак (20 шт),"0,069","14,000","14,800",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [175]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 972 entries, 0 to 971
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Код          972 non-null    object
 1   шт в упак    972 non-null    object
 2   м3 упак      968 non-null    object
 3   нетто упак   962 non-null    object
 4   брутто упак  968 non-null    object
 5   Unnamed: 5   0 non-null      float64
 6   Unnamed: 6   0 non-null      float64
 7   Unnamed: 7   0 non-null      float64
 8   Unnamed: 8   0 non-null      float64
 9   Unnamed: 9   0 non-null      float64
 10  Unnamed: 10  0 non-null      float64
 11  Unnamed: 11  0 non-null      float64
 12  Unnamed: 12  0 non-null      float64
 13  Unnamed: 13  0 non-null      float64
dtypes: float64(9), object(5)
memory usage: 106.4+ KB

## Transform

### Удаение пустых столбцов

In [176]:
df = df.drop(df.columns[5:], axis=1)

In [177]:
df.head()

,Код,шт в упак,м3 упак,нетто упак,брутто упак
0,"PFAN-1107, Döcke Наличник 89 мм/ 30 мм (Белый)",упак (14 шт),"0,146","21,168","22,548"
1,"PFAN-1193, Döcke Наличник 89 мм/ 30 мм (Шокола...",упак (14 шт),"0,146","21,168","22,548"
2,"PFAV-1107, Döcke Внешний угол 75 мм/ 30 мм (Бе...",упак (8 шт),"0,145","15,552","16,788"
3,"PFAV-1193, Döcke Внешний угол 75 мм/ 30 мм (Шо...",упак (8 шт),"0,145","15,552","16,788"
4,"PFPF-1039, Döcke Профиль J18 (Карамельный)",упак (20 шт),"0,069","14,000","14,800"

In [178]:
df.columns

Index(['Код', 'шт в упак', 'м3 упак', 'нетто упак', 'брутто упак'], dtype='object')

### Столбец - код

In [179]:
df[['Code', 'Data']] = df['Код'].str.split(',', n=1, expand=True)
df.head()

,Код,шт в упак,м3 упак,нетто упак,брутто упак,Code,Data
0,"PFAN-1107, Döcke Наличник 89 мм/ 30 мм (Белый)",упак (14 шт),"0,146","21,168","22,548",PFAN-1107,Döcke Наличник 89 мм/ 30 мм (Белый)
1,"PFAN-1193, Döcke Наличник 89 мм/ 30 мм (Шокола...",упак (14 шт),"0,146","21,168","22,548",PFAN-1193,Döcke Наличник 89 мм/ 30 мм (Шоколадный)
2,"PFAV-1107, Döcke Внешний угол 75 мм/ 30 мм (Бе...",упак (8 шт),"0,145","15,552","16,788",PFAV-1107,Döcke Внешний угол 75 мм/ 30 мм (Белый)
3,"PFAV-1193, Döcke Внешний угол 75 мм/ 30 мм (Шо...",упак (8 шт),"0,145","15,552","16,788",PFAV-1193,Döcke Внешний угол 75 мм/ 30 мм (Шоколадный)
4,"PFPF-1039, Döcke Профиль J18 (Карамельный)",упак (20 шт),"0,069","14,000","14,800",PFPF-1039,Döcke Профиль J18 (Карамельный)

### Столбец - цвет

In [180]:
def extract_color(text):
  text = str(text).strip()
  # if color in ()
  result = re.search(r"\((.*?)\)\s*$", text)
  if result:
    return result.group(1).strip()

  #if color after / or //
  result = re.search(r"/+\s*([^/]+)$", text)
  if result:
    return result.group(1).strip()

def remove_text(row, column_name):
    text = str(row['Data']).strip()
    value = row[column_name]

    if value:
        text = text.replace(value, '')
        text = ' '.join(text.split())
        text = text.replace('()', '').replace('( )', '')
        text = text.rstrip('/').strip()

    return text.strip()

df['Color'] = df['Data'].apply(extract_color)
df['Data'] = df.apply(remove_text, axis=1, column_name='Color')

### Столбец - размер

In [181]:
def extract_size(text):
  text = str(text).strip()
  size_patterns = [
      r'(\d+\s*)(?:мм|см|м)?(\s*[*хx/]\s*)(\d+\s*)(?:мм|см|м)?(\s*[*хx/]\s*)?(\d+\s*)?(?:мм|см|м)?',
      r"(\d+\s*)(?:мм|см|м)",                           # 120 мм
      r"[A-Za-zА-Яа-я]\d+",                             # D120, J18
      r"(\d+\s*)(?:мм|см|м)(\s*[*хx/]\s*)(\d+\s*[˚°])"  # 80 мм * 45˚
      ]
  for p in size_patterns:
    result = re.search(p + r"\s*$", text, flags=re.IGNORECASE)
    if result:
      return result.group(0)
  return None

df['Size'] = df['Data'].apply(extract_size)
df['Data'] = df.apply(remove_text, axis=1, column_name='Size')

### Столбец - бренд

In [182]:
def extract_brand(text):
  text = str(text).strip()
  brand_patterns = r"\b(Döcke|Docke|Dӧcke)\b"

  result = re.search(brand_patterns, text, flags=re.IGNORECASE)
  if result:
    return result.group(0)
  return None

df['Brand'] = df['Data'].apply(extract_brand)
df['Data'] = df.apply(remove_text, axis=1, column_name='Brand')

### Столбец - наименование

In [183]:
def extract_name(text):
    text = str(text).strip()

    result = re.search(r'([а-яА-ЯёЁ][а-яА-ЯёЁ\s-]*[а-яА-ЯёЁ])', text)
    if result:
      return result.group(0)

df['Name'] = df['Data'].apply(extract_name)

Очистка столбца наименование от серий

In [184]:
def remove_series(text):
  text=str(text).strip()

  series_list = ['PREMIUM', 'LUX', 'STANDARD','Standart', 'PIE', 'STEIN', 'KLINKER', 'FIX',
                 'GLASS', 'STAL', 'Comfort', 'EL', 'PLUS', 'BRICK', 'BERGART', 'BURG','FELS',
                 'DRAGON', 'STERN', 'COTA', 'EUROPA', 'KARAT', 'ROCKY', 'EURASIA', 'RA', 'DACHA',
                 'MONTERREY', 'NEXT', 'ROOT', 'BERG', 'MATRIX', 'SLATE', 'СОТА',
                 'ЭДЕЛЬ', 'НИЦЦА', 'САППОРО', 'ЖЕНЕВА', 'ГЕНУЯ', 'ЦЮРИХ', 'КЁЛЬН', 'ТЕТРИС','ФЛЕМИШ',
                 'СЛАНЕЦ', 'СЛАНЕЦ', 'ДЮФУР', 'АЛТАЙ', 'ШЕФФИЛД', 'КРОНА', 'ЛАБИРИНТ', 'ПЛИТКА', 'ШЕСТИГРАННИК',
                 'Монреаль']
  for s in series_list:
    text = re.sub(rf'\b{re.escape(s)}\b', '', text, flags=re.IGNORECASE)

  text = re.sub(r'^[\s/,]+', '', text)
  text = re.sub(r'[\s/,]+$', '', text)
  text = re.sub(r'\s+', ' ', text)

  return text.strip()

df['Name'] = df['Data'].apply(remove_series)

Очистка столбца цвет, ручное исправление ошибок

In [185]:
df['Color'].unique()

array(['Белый', 'Шоколадный', 'Карамельный', 'Дымчатый', 'Палевый',
       'Каштановый', 'Табачный', 'Банан', 'Голубика', 'Капучино',
       'Карамель', 'Киви', 'Крем-брюле', 'Лимон', 'Пломбир', 'Сливки',
       'Фисташки', 'Халва', 'Шоколад', 'Графит', 'Олива', 'Слива',
       'Манго', 'Каштан', 'Персик', None, 'Латте', 'Карбон', 'Кофе',
       'Арахис', 'Изюм', 'Фладен', 'Чили', 'Вагаси', 'Янтарный',
       'Песчаный', 'Клубника', 'Зрелый каштан', 'Кирпичный', 'Коричневый',
       'Серый', 'Рубиновый', 'Золотой', 'Желтый жженый', 'Красный жженый',
       '5кг', 'Кешью', 'Пекан', 'Кокос', 'Кедровый орех', 'Орех',
       'Миндаль', 'Рябина', 'Кедр', 'Канадская береза', 'Платиновый',
       'Тёмный', 'Льняной', 'Оливковый', 'Кукурузный', 'Цвет шерсти',
       'Земляной', 'Пшеничный', 'Слоновая кость', 'Терракотовый',
       'Перламутровый', 'Ржаной', 'Арктик', 'Горный хрусталь', 'Молочный',
       'Осенний лес', 'Тёмный орех', 'Базальт', 'Антрацит', 'Бронза',
       'Темно-коричневый', 'Зеленый', 'Серый 7024', 'Светло-коричневый',
       'Красный 3005', 'Зелёный 6005', 'Белый 9003',
       'Светло-коричневый 8017', 'Тёмно-коричневый 8019', 'Канноли',
       'Какао', 'Трюфель', 'Амаретто', 'Ежевика', 'Черника', 'Красный',
       'Окисленная медь', 'Мускат', 'Антик', 'Навахо', 'Марракеш',
       'Мармарис', 'Родос', 'Дакота', 'Каштан 8017', 'Пломбир 9010',
       'Шоколад 8019', 'Графит 7024', 'оцинков.сталь', 'Анис-Розмарин',
       'Кунжут-Миндаль', 'Тирамису', 'Фладен-Канноли', 'Корица', 'Мята',
       'Чернослив', 'Бисквит', 'Инжир-Клубника', 'Брауни-Арахис',
       'Изюм-Слива', 'Имбирь', 'Барбарис', 'Грильяж', 'Крем-Брюле',
       'Каракумы', 'Сахара', 'Калахари', 'Атакама', 'Монте', 'Синий',
       'Медный', 'Кофейный', '5 л', '10 л', 'шоколад', 'Куршевель',
       'Валь-Гардена', 'Церматт', 'Шамони', 'Лех', 'Виллар', 'Давос',
       'Зёльден', 'Инсбрук', 'Ишгль', 'Кремовый', 'Зелёный', 'Корунд',
       'Родонит', 'Циркон', 'Берилл', 'Агатовый', 'Графитовый',
       'Тёмно-коричневый', 'Светло-Коричневый', 'Яблоня', 'Фундук',
       'Стартовый профиль', 'каштан 8017', 'зеленый 6005', 'пломбир 9003',
       'шоколад 8019', 'гранат RR29', 'графит 7024', 'красный 3005',
       'Брауни', 'Тёмно-серый'], dtype=object)

In [186]:
wrong_names = ['Стартовый профиль', '5кг', '5 л', '10 л']

problem_indices = df[df['Color'].isin(wrong_names)].index.tolist()

print(f"Найдено индексов: {len(problem_indices)}")
print(problem_indices)

Найдено индексов: 4
[344, 661, 662, 896]

In [187]:
df.loc[344, 'Color']=''
df.loc[661, 'Color']=''
df.loc[662, 'Color']=''
df.loc[896, 'Color']=''
df.loc[896, 'Name']='Стартовый профиль'

### Столбец - штук

In [188]:
def extract_quantity(text):
  text = str(text).strip()
  result = re.search(r'\d+', text)
  if result:
    return int(result.group(0))

df['quantity'] = df['шт в упак'].apply(extract_quantity)
df['quantity'] = df['quantity'].fillna(0)

### Столбец - м3 на урпаковку

In [189]:
# replace , to .
df['м3 упак'] = df['м3 упак'].astype(str).str.replace(',', '.')

df['m3_per_one'] = pd.to_numeric(df['м3 упак'], errors='coerce')
df['m3_per_one'] = df['m3_per_one'].fillna(0) #fill nan

df['m3_per_one'] = np.where(df['quantity'] == 0, 0, df['m3_per_one'] / df['quantity'])

### Столбец - брутто упаковки

In [190]:
# replace , to .
df['брутто упак'] = df['брутто упак'].astype(str).str.replace(',', '.')

df['gross_per_one'] = pd.to_numeric(df['брутто упак'], errors='coerce')
df['gross_per_one'] = df['gross_per_one'].fillna(0) #fill nan

df['gross_per_one'] = np.where(df['quantity'] == 0, 0, df['gross_per_one'] / df['quantity'])

## Load

### Выгрузка в Excel

In [191]:
data = df[['Code', 'Brand', 'Name', 'Size', 'Color', 'quantity', 'm3_per_one', 'gross_per_one']]
data

,Code,Brand,Name,Size,Color,quantity,m3_per_one,gross_per_one
0,PFAN-1107,Döcke,Наличник,89 мм/ 30 мм,Белый,14.0,0.010429,1.610571
1,PFAN-1193,Döcke,Наличник,89 мм/ 30 мм,Шоколадный,14.0,0.010429,1.610571
2,PFAV-1107,Döcke,Внешний угол,75 мм/ 30 мм,Белый,8.0,0.018125,2.098500
3,PFAV-1193,Döcke,Внешний угол,75 мм/ 30 мм,Шоколадный,8.0,0.018125,2.098500
4,PFPF-1039,Döcke,Профиль,J18,Карамельный,20.0,0.003450,0.740000
...,...,...,...,...,...,...,...,...
967,ZRSN-1081,Döcke,Гибкая черепица,None,Фладен,42.0,0.030000,0.000000
968,ZRSN-1114,Döcke,Гибкая черепица,None,Красный,42.0,0.030000,0.000000
969,ZRSU-1078,Döcke,Гибкая черепица,None,Кофе,32.0,0.039375,0.000000
970,ZRSU-1162,Döcke,Гибкая черепица,None,Вагаси,32.0,0.039375,0.000000
971,ZRSU-1175,Döcke,Гибкая черепица,None,Зрелый каштан,32.0,0.039375,0.000000

In [192]:
data.to_excel('data.xlsx', index=False)